sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ibarreche/cloud-back-test -f ./app/back/Dockerfile.test ./app/back

script:
  - docker run -e CI=true ibarreche/cloud-back-test ./vendor/bin/phpunit

after_success:
  - docker build -t ibarreche/cloud-back-ci ./app/back
  - docker build -t ibarreche/cloud-front-ci:coin ./app/front
  - docker build -t ibarreche/cloud-indexer-ci ./app/indexer
  - docker build -t ibarreche/cloud-nginx-ci ./app/nginx
  - docker build -t ibarreche/cloud-reporting-ci ./app/reporting

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ibarreche/cloud-back-ci
  - docker push ibarreche/cloud-front-ci:coin
  - docker push ibarreche/cloud-indexer-ci
  - docker push ibarreche/cloud-nginx-ci
  - docker push ibarreche/cloud-reporting-ci