sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ibarreche/cloud-back-test -f ./app/back/Dockerfile.test ./app/back

script:
  - docker run -e CI=true ibarreche/cloud-back-test ./vendor/bin/phpunit

after_success:
  - docker build -t ibarreche/cloud-frontend-ci ./app/client
  - docker build -t ibarreche/cloud-back-ci ./app/back
  # Log in to the docker CLI
  #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  #- docker push ibarreche/cloud-frontend
  #- docker push ibarreche/cloud-back
