apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.role_manage.namespace}}
  name: {{ .Values.role_manage.name}}
rules:
- apiGroups: [""]
  resources:
    {{- range .Values.role_manage.pod_resources }}
      - {{ . | quote }}
    {{- end }}   
  verbs: 
    {{- range .Values.role_manage.pod_verbs }}
      - {{ . | quote }}
    {{- end }}
- apiGroups: {{ .Values.role_manage.deploy_api}}
  resources:
    {{- range .Values.role_manage.deploy_resources }}
      - {{ . | quote }}
    {{- end }}
  verbs:
    {{- range .Values.role_manage.deploy_verbs }}
      - {{ . | quote }}
    {{- end }}
- apiGroups: {{ .Values.role_manage.role_api}}
  resources:
    {{- range .Values.role_manage.role_resources }}
      - {{ . | quote }}
    {{- end }}
  verbs:
    {{- range .Values.role_manage.role_verbs }}
      - {{ . | quote }}
    {{- end }}
- apiGroups: {{ .Values.role_manage.ingress_api}}
  resources:
    {{- range .Values.role_manage.ingress_resources }}
      - {{ . | quote }}
    {{- end }}
  verbs:
    {{- range .Values.role_manage.ingress_verbs }}
      - {{ . | quote }}
    {{- end }}
- apiGroups: {{ .Values.role_manage.cron_api}}
  resources:
    {{- range .Values.role_manage.cron_resources }}
      - {{ . | quote }}
    {{- end }}
  verbs:
    {{- range .Values.role_manage.cron_verbs }}
      - {{ . | quote }}
    {{- end }}