apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.role_binding_manage.name}}
  namespace: {{ .Values.role_binding_manage.namespace}}
subjects:
- kind: User
  name: {{ .Values.role_binding_manage.username}}
  apiGroup: {{ .Values.role_binding_manage.apiGroup}}
roleRef:
  kind: Role
  name: {{ .Values.role_binding_manage.name}}
  apiGroup: {{ .Values.role_binding_manage.apiGroup}}