apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.role_monitoring.namespace}}
  name: {{ .Values.role_monitoring.name}}
rules:
- apiGroups: [""]
  resources:
    {{- range .Values.role_monitoring.pod_resources }}
      - {{ . | quote }}
    {{- end }}  
  verbs:
    {{- range .Values.role_monitoring.pod_verbs }}
      - {{ . | quote }}
    {{- end }} 
- apiGroups: {{ .Values.role_monitoring.deploy_api}}
  resources:
    {{- range .Values.role_monitoring.deploy_resources }}
      - {{ . | quote }}
    {{- end }} 
  verbs:
    {{- range .Values.role_monitoring.deploy_verbs }}
      - {{ . | quote }}
    {{- end }} 
- apiGroups: {{ .Values.role_monitoring.customresources_api}}
  resources:
    {{- range .Values.role_monitoring.customresources_resources }}
      - {{ . | quote }}
    {{- end }} 
  verbs: 
    {{- range .Values.role_monitoring.customresources_verbs }}
      - {{ . | quote }}
    {{- end }} 
- apiGroups: {{ .Values.role_monitoring.policy_api}}
  resources: 
    {{- range .Values.role_monitoring.policy_resources }}
      - {{ . | quote }}
    {{- end }} 
  verbs: 
    {{- range .Values.role_monitoring.policy_verbs }}
      - {{ . | quote }}
    {{- end }} 
  