sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ibarreche/cloud-back-test ./back

script:
  - docker run -e CI=true ibarreche/cloud-back-test ./vendor/bin/phpunit

after_success:
  - docker build -t ibarreche/cloud-frontend ./client
  - docker build -t ibarreche/cloud-back ./back
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ibarreche/cloud-frontend
  - docker push ibarreche/cloud-back
