version: '3.9'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    depends_on:
      - front
      - api
    ports:
      - '4000:80'
  front:
    build:
      dockerfile: Dockerfile
      context: ./front
    # ports:
    #   - '4200:4200'
    volumes:
      - /app/node_modules
      - ./front:/app
  api:
    build:
      dockerfile: Dockerfile
      context: ./back
    # image: ibarreche/cloud-test
    # ports:
    #   - '8000:8000'
    depends_on:
      - laravel-db
    volumes:    
      - /var/www/html/vendor
      - ./back:/var/www/html:cached

  laravel-db:
    image: mysql:5.6
    ports:
     - "3306:3306"
    env_file:
      - ./back/.env
    volumes:
      - laravel-db:/var/lib/mysql
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3306"]
        interval: 30s
        timeout: 10s
        retries: 5

volumes:
  laravel-db:
