apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: devops
  name: manage-pods
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/portforward", "services", "pods/log", "secrets", 'configmaps', "serviceaccounts", "endpoints", "events"]
  verbs: ["get", "watch", "list", "create"]
- apiGroups: ["apps"]
  resources: ["deployments","statefulsets"]
  verbs: ["get", "watch", "list", "create"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "create"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "watch", "list", "create"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["get", "watch", "list", "create", "delete"]