apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitor-pods
  namespace: monitoring
subjects:
- kind: User
  name: "Tom Ibarreche"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: monitor-pods
  apiGroup: rbac.authorization.k8s.io