apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app : {{ .Values.elasticsearch_deployment.name }}
    component: {{ .Values.elasticsearch_deployment.name }}
    release: {{ .Values.elasticsearch_deployment.name }}
  name: {{ .Values.elasticsearch_deployment.name }}
spec:
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app : {{ .Values.elasticsearch_deployment.name }}
      component: {{ .Values.elasticsearch_deployment.name }}
      release: {{ .Values.elasticsearch_deployment.name }}
  serviceName: {{ .Values.elasticsearch_deployment.name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app : {{ .Values.elasticsearch_deployment.name }}
        component: {{ .Values.elasticsearch_deployment.name }}
        release: {{ .Values.elasticsearch_deployment.name }}
    spec:
      containers:
      - env:
        - name: cluster.name
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.elasticsearch_configMap.name }}
              key: elasticsearch_cluster_name
        - name: discovery.type
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.elasticsearch_configMap.name }}
              key: elasticsearch_discovery_type
        - name: ES_JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.elasticsearch_configMap.name }}
              key: elasticsearch_es_java_opts
        - name: bootstrap.memory_lock
          value: "true"
        image: elasticsearch:7.17.3
        imagePullPolicy: IfNotPresent
        name: {{ .Values.elasticsearch_deployment.name }}
        ports:
        - containerPort: {{ .Values.elasticsearch_deployment.containerPortHttp }}
          name: http
          protocol: TCP
        - containerPort: {{ .Values.elasticsearch_deployment.containerPortTcp }}
          name: transport
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 150m
            memory: 512Mi
        securityContext:
          privileged: true
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-data
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - chown -R 1000:1000 /usr/share/elasticsearch/data
        - sysctl -w vm.max_map_count=262144
        - chmod 777 /usr/share/elasticsearch/data
        - chomod 777 /usr/share/elasticsearch/data/node
        - chmod g+rwx /usr/share/elasticsearch/data
        - chgrp 1000 /usr/share/elasticsearch/data
        image: busybox:1.29.2
        imagePullPolicy: IfNotPresent
        name: set-dir-owner
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-data
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: elasticsearch-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
